### ISSUE TITLE
[Bug]: linode_object_storage_key not updated when changing permissions

### ISSUE THREAD

**Issue by Aransh** [linode/terraform-provider-linode#905] opened 2023-06-22 13:31 UTC
### Terraform Version

v1.5.0

### Linode Provider Version

v2.5.0

### Effected Terraform Resources

linode_object_storage_key

### Terraform Config Files
```terraform
resource "linode_object_storage_key" "this" {
    label      = "<redacted>"
    limited    = true

    bucket_access {
        bucket_name = "<redacted>"
        cluster     = "us-southeast-1"
        permissions = "read_only"
    }
    bucket_access {
        bucket_name = "<redacted>"
        cluster     = "us-southeast-1"
        permissions = "read_write"
    }
}
```

### Expected Behavior

When changing the buckets an access key has access to, I expect the provider to update the access key.
If it can not but updated like this, then I expect it to "replace" the existing key with a new one with the new permissions.

### Actual Behavior

The access key does not change at all, running "terraform apply" again and again produces the same plan which never actually applies.

### Steps to Reproduce

Create a linode_object_storage_key resource with specific "bucket_access" blocks.
Then, try changing the buckets in the "bucket_access" block.
Result - plan never applies

**Comment by lgarber-akamai** [comment] 2023-06-22 14:44
Thanks for the bug report!

I was able to reproduce this issue on the latest version of the provider. Just for reference, the expected behavior is that any permission changes trigger a recreation of the key.

Fortunately, I've confirmed that this issue is resolved in the [migration of the `linode_object_storage_key` from SDKv2 to Framework](https://github.com/linode/terraform-provider-linode/pull/902), which will be going out in our next release.

Let us know if you discover any other issues :slightly_smiling_face:

**Comment by Aransh** [comment] 2023-06-25 08:51
Sounds great, looking forward to the release
Thanks :)

**Comment by Aransh** [comment] 2023-07-27 06:48
Not stale

**Comment by zliang-akamai** [comment] 2023-10-03 03:26
I think this issue has been resolved in the newer version of the provider. 
I tried:

```terraform
resource "linode_object_storage_key" "this" {
    label      = "some_test_buckets_key"
    bucket_access {
        bucket_name = "some_bucket"
        cluster     = "us-southeast-1"
        permissions = "read_only"
    }
    bucket_access {
        bucket_name = "some_bucket2"
        cluster     = "us-southeast-1"
        permissions = "read_write"
    }
}
```

And then update it to:

```terraform
resource "linode_object_storage_key" "this" {
    label      = "some_test_buckets_key"
    bucket_access {
        bucket_name = "some_bucket"
        cluster     = "us-southeast-1"
        permissions = "read_only"
    }
}
```

Everything seems to be working as expected. Please let us know if this is still an issue. Thank you again for the report!

**Closed by zliang-akamai** 2023-10-03 03:26 UTC
Labels: bug, keep
