### ISSUE TITLE
[Bug]: Inconsistent final plan for CNAME record

### ISSUE THREAD

**Issue by Routhinator** [linode/terraform-provider-linode#572] opened 2021-12-26 22:11 UTC
### Terraform Version

Terraform v1.0.10 on linux_amd64

### Linode Provider Version

v1.25.0

### Effected Terraform Resources

linode_domain_record

### Panic Output

╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for linode_domain_record.smtp_routh_io to include new values learned so far during apply, provider "registry.terraform.io/linode/linode" produced an invalid
│ new value for .target: was cty.StringVal("lb.prod.routh.io"), but now cty.StringVal("lb").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

### Expected Behavior

CNAME is created with `lb.prod.routh.io` as the target

### Actual Behavior

CNAME plan shows target as `lb`

### Steps to Reproduce

```hcl
resource "linode_domain_record" "at_routh_io" {
  name        = linode_domain.routh_io.domain
  domain_id   = linode_domain.routh_io.id
  record_type = "CNAME"
  ttl_sec     = "3600"
  target      = "lb.prod.routh.io"
}
```

**Comment by LBGarber** [comment] 2022-02-24 18:42
@Routhinator Just checking in to see if this issue is still occurring for you.

**Comment by LBGarber** [comment] 2022-03-11 14:36
Since we haven't been able to reproduce this issue I'm going to close it for now. 
Feel free to let us know if this issue pops up again :slightly_smiling_face:

**Closed by LBGarber** 2022-03-11 14:36 UTC
Labels: bug
